# CSV 文件读取与数据查询

本 Notebook 用于读取 CDC 特征文件并进行数据查询和探索。

# boss特征

In [2]:
# 导入必要的库
import json
from pathlib import Path
import numpy as np
import pandas as pd

# 禁用科学计数法，显示完整数值（保留完整精度）
pd.set_option('display.float_format', lambda x: f'{x:.10f}'.rstrip('0').rstrip('.'))

# print("库导入成功！")
# 读取 CSV 文件
# 注意：pd.read_csv() 使用 index_col 参数指定索引列，而不是 index

# 指定要读取的文件
csv_file_con = 'cdc_v3_consultas.csv'
csv_api_con = 'consultas_02281519.csv'
csv_file_cre = 'cdc_v3_creditos.csv'
csv_api_cre = 'creditos_02281522.csv'
csv='cdc.csv'

# 读取数据
data_con= pd.read_csv(csv_file_con)
api_con = pd.read_csv(csv_api_con)
data_cre = pd.read_csv(csv_file_cre)
api_cre = pd.read_csv(csv_api_cre)
csv = pd.read_csv(csv)

库导入成功！

In [8]:
# data_con
# data_cre
# api_con
# api_cre
# csv

In [9]:
csv[(csv['apply_id'] ==1102041191718100993)]

                 apply_id       cust_no              create_time
9262  1102041191718100993  800001520343  2025-12-07 05:20:20.705

In [10]:

data_con[(data_con['apply_id'] == 1102041191718100993)][['win_36000d_amt_mean']]

      win_36000d_amt_mean
9262            5454807.5

In [11]:
api_con[(api_con['apply_id'] == 1102041191718100993)][['win_36000d_amt_mean']]

      win_36000d_amt_mean
9262   5454807.2727272725

In [12]:
data_cre[(data_cre['apply_id'] == 1102041191718100993)][['cr_lastbuy_freq_Monthly_720d_avg_limit']]

      cr_lastbuy_freq_Monthly_720d_avg_limit
9262                               8044.8945

In [13]:
api_cre[(api_cre['apply_id'] == 1102041191718100993)][['cr_lastbuy_freq_Monthly_720d_avg_limit']]

      cr_lastbuy_freq_Monthly_720d_avg_limit
9262                         8044.8947368421